version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: webhook_user
      POSTGRES_PASSWORD: webhook_password
      POSTGRES_DB: webhooks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    image: saihrieshikesh/webhook-api:latest
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://webhook_user:webhook_password@postgres:5432/webhooks_db
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    depends_on:
      - postgres
      - redis

  worker:
    image: saihrieshikesh/webhook-worker:latest
    build: ./worker
    environment:
      - DATABASE_URL=postgres://webhook_user:webhook_password@postgres:5432/webhooks_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  receiver:
    image: saihrieshikesh/webhook-receiver:latest
    build: ./receiver
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

volumes:
  postgres_data:
